Update patch set 6
Patch Set 6: Verified-1

The smoke tests build now. 829 of 902 tests pass.

Checkstyle errors:

ERROR (google3/tmp/google3/third_party/java_src/gwt/svn/trunk/user/test/com/google/gwt/i18n/client/GwtLocaleInfo_en_US_Test.java:20) -- Missing a Javadoc comment. (com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocTypeCheck)
ERROR (google3/tmp/google3/third_party/java_src/gwt/svn/trunk/user/test/com/google/gwt/i18n/server/JavaLocaleInfo_en_US_Test.java:22) -- Missing a Javadoc comment. (com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocTypeCheck)
ERROR (google3/tmp/google3/third_party/java_src/gwt/svn/trunk/user/test/com/google/gwt/i18n/server/ServerNumberFormat_en_Test.java:19.8) -- Unused import - com.google.gwt.i18n.shared.NumberFormat. (com.puppycrawl.tools.checkstyle.checks.imports.UnusedImportsCheck)
ERROR (google3/tmp/google3/third_party/java_src/gwt/svn/trunk/user/test/com/google/gwt/i18n/shared/LocaleInfo_en_US_TestBase.java:21) -- Missing a Javadoc comment. (com.puppycrawl.tools.checkstyle.checks.javadoc.JavadocTypeCheck)

apicheck errors:
     [java] Found 38 new resources
     [java] Checking for compile errors
     [java]    [ERROR] Errors in '/build/work/1e8e8d638b6c273a0585320df2391b7e/google3/tmp/google3/third_party/java_src/gwt/svn/trunk/./user/src/com/google/gwt/i18n/shared/cldr/LocaleInfoImpl_ta_IN.java'
     [java]       [ERROR] Line 30: The type LocaleInfoImpl_ta_IN is already defined
     [java]    [ERROR] Errors in '/build/work/1e8e8d638b6c273a0585320df2391b7e/google3/tmp/google3/third_party/java_src/gwt/svn/trunk/./user/src/com/google/gwt/i18n/shared/cldr/LocaleInfoImpl_en_PH.java'
     [java]       [ERROR] Line 32: The type LocaleInfoImpl_en_PH is already defined
     [java]    [ERROR] Errors in '/build/work/1e8e8d638b6c273a0585320df2391b7e/google3/tmp/google3/third_party/java_src/gwt/svn/trunk/./user/src/com/google/gwt/i18n/shared/cldr/LocaleInfoImpl_es_CO.java'
     [java]       [ERROR] Line 32: The type LocaleInfoImpl_es_CO is already defined
     [java]    [ERROR] Errors in 
[...]

In CoreSuite:

com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
	at com.google.gwt.dev.StrictModeTest.precompile(StrictModeTest.java:112)
	at com.google.gwt.dev.StrictModeTest.testGoodCompileStrict(StrictModeTest.java:91)

junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at com.google.gwt.dev.StrictModeTest.testGoodValidateStrict(StrictModeTest.java:106)

In I18nSuite:

java.lang.NullPointerException
	at com.google.gwt.i18n.client.LocaleInfo_ar_Test.testNativeDisplayNames(LocaleInfo_ar_Test.java:50)

junit.framework.AssertionFailedError: Remote test failed at 127.0.0.1 / Mozilla/5.0 (X11; U; Linux i686 (x86_64); en-US; rv:1.9.2.3) Gecko/20100401 Firefox/3.6.3
expected: <50>, actual: <56>
	at junit.framework.Assert.fail(Assert.java:193)
	at junit.framework.Assert.failNotEquals(Assert.java:198)
	at junit.framework.Assert.assertEquals(Assert.java:94)
	at junit.framework.Assert.assertEquals(Assert.java:43)
	at com.google.gwt.i18n.client.RuntimeLocalesTest.testAvailable(RuntimeLocalesTest.java:35)


In ConstraintCompositionCompileTest.testOverriddenAttributesMustMatchInType:
java.lang.AssertionError: Errors in 'jar:file:/build/cas/fdf/fdf146a8526d1049f5e07e10e9ecb00a!/com/google/gwt/i18n/client/ConstantMapTest.java'
	at com.google.gwt.dev.shell.FailErrorLogger.branch(FailErrorLogger.java:29)
	at com.google.gwt.core.ext.TreeLogger.branch(TreeLogger.java:222)
	at com.google.gwt.dev.javac.CompilationProblemReporter.reportErrors(CompilationProblemReporter.java:200)
	at com.google.gwt.dev.javac.CompilationStateBuilder.compile(CompilationStateBuilder.java:339)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:463)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:388)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:373)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:367)
	at org.hibernate.jsr303.tck.util.TckGeneratorTestUtils.createGeneratorContext(TckGeneratorTestUtils.java:54)
	at org.hibernate.jsr303.tck.util.TckCompileTestCase.setUp(TckCompileTestCase.java:76)

And similar issues in other validation suite tests.

Patch-set: 6
Reviewer: Gerrit User 5010 <5010@84fdd5b9-d3fc-3149-9ae9-e619898c4c46>
Label: Verified=-1