Update patch set 3
Patch Set 3:

At least locally, I'm getting a test failure that appears to stem from this:

Testcase: testConstructor took 0.056 sec
	FAILED
NullPointerException must be thrown if any constructor parameter is null
junit.framework.AssertionFailedError: NullPointerException must be thrown if any constructor parameter is null
	at java.lang.Throwable.Throwable(Throwable.java:75)
	at java.lang.Error.Error(Error.java:30)
	at java.lang.AssertionError.AssertionError(AssertionError.java:51)
	at junit.framework.AssertionFailedError.AssertionFailedError(AssertionFailedError.java:27)
	at com.google.gwt.emultest.java8.util.StringJoinerTest.testConstructor(StringJoinerTest.java:44)

Patch-set: 3