Update patch set 5
Patch Set 5:

This broke many compiles:

java.lang.AssertionError: Current child removal is not supported by com.google.gwt.thirdparty.common.css.compiler.ast.DefaultVisitController$VisitDefinitionState VisitState class.
	at com.google.gwt.thirdparty.common.css.compiler.ast.DefaultVisitController$BaseVisitState.removeCurrentChild(DefaultVisitController.java:136)
	at com.google.gwt.thirdparty.common.css.compiler.ast.DefaultVisitController$VisitFunctionNodeState.removeCurrentNodeCalled(DefaultVisitController.java:1601)
	at com.google.gwt.thirdparty.common.css.compiler.ast.DefaultVisitController.removeCurrentNode(DefaultVisitController.java:2005)
	at com.google.gwt.thirdparty.common.css.compiler.passes.ResolveCustomFunctionNodes.leaveFunctionNode(ResolveCustomFunctionNodes.java:189)
	at com.google.gwt.thirdparty.common.css.compiler.ast.DefaultVisitController$VisitFunctionNodeState.doVisit(DefaultVisitController.java:1575)
	at com.google.gwt.thirdparty.common.css.compiler.ast.DefaultVisitController.startVisit(DefaultVisitController.java:2028)
	at com.google.gwt.thirdparty.common.css.compiler.passes.ResolveCustomFunctionNodes.runPass(ResolveCustomFunctionNodes.java:231)
	at com.google.gwt.resources.rg.GssResourceGenerator.optimizeTree(GssResourceGenerator.java:762)
	at com.google.gwt.resources.rg.GssResourceGenerator.createAssignment(GssResourceGenerator.java:404)
	at com.google.gwt.resources.rg.CssResourceGenerator.createAssignment(CssResourceGenerator.java:444)
	at com.google.gwt.resources.rebind.context.AbstractClientBundleGenerator.createFieldsAndAssignments(AbstractClientBundleGenerator.java:752)
	at com.google.gwt.resources.rebind.context.AbstractClientBundleGenerator.createFieldsAndAssignments(AbstractClientBundleGenerator.java:821)
	at com.google.gwt.resources.rebind.context.AbstractClientBundleGenerator.generateIncrementally(AbstractClientBundleGenerator.java:469)
	at com.google.gwt.dev.javac.StandardGeneratorContext.runGeneratorIncrementally(StandardGeneratorContext.java:739)
	at com.google.gwt.dev.cfg.RuleGenerateWith.realize(RuleGenerateWith.java:103)

Patch-set: 5
Reviewer: Gerrit User 5385 <5385@84fdd5b9-d3fc-3149-9ae9-e619898c4c46>
Label: Verified=0