Update patch set 6
Patch Set 6:

Also failing 

java.lang.NoClassDefFoundError: com/google/gson/JsonParseException
	at com.google.gwt.thirdparty.debugging.sourcemap.SourceMapGeneratorV3.mergeMapSection(SourceMapGeneratorV3.java:310)
	at com.google.gwt.core.linker.SymbolMapsLinker.link(SymbolMapsLinker.java:316)
	at com.google.gwt.core.ext.linker.impl.StandardLinkerContext.invokeLinkForOnePermutation(StandardLinkerContext.java:384)
	at com.google.gwt.dev.Link.finishPermutation(Link.java:483)

This seems to be due to missing dependencies (gson) that were previously bundled in the closure jar.

Please run the tests next time before oking the cl.

Patch-set: 6