Fixes overlay type rewriting.  Previously, all JSO implementation classes subclassed Object.  However, this causes NoSuchMethodErrors in cases where client code accesss a static method in a superclass using a subclass as a qualifier.
Found by: zundel
Review by: jat (desk)


git-svn-id: https://google-web-toolkit.googlecode.com/svn/releases/1.5@3368 8db76d5a-ed1c-0410-87a9-c151d255dfc7