Update patch set 3
Patch Set 3:

> > The test seems like disabled checking?
 > 
 > str.toString()
 > replaced to
 > String.valueOf(str)
 > which returns "null" for null values

Btw, with current master I have
Caused by: java.lang.NoSuchMethodError: java.lang.StringBuilder.toString()Ljava/lang/String;

when compiling code in SDM

It's code by method reference StringBuilder::toString in Collectors.java

Patch-set: 3