Update patch set 2
Patch Set 2:

Hm, this patch is breaking the RPCSuite tests, but I can't quite figure out why.

I see these warnings in the test logs that I think are related:

   [WARN] com.google.gwt.junit.server.JUnitHostImpl-14480949: An IncompatibleRemoteServiceException was thrown while processing this call.
com.google.gwt.user.client.rpc.IncompatibleRemoteServiceException: This application is out of date, please click the refresh button on your browser. ( Malformed or old RPC message received - expecting version between 5 and 7 )


Warning: Retrying syncing back to junit backend. (Exception: java.lang.StringIndexOutOfBoundsException: String index out of range: 256)


I think we'll need to revert this change and try again unless you have an idea of how to fix it.

Patch-set: 2