Update patch set 4
Patch Set 4: Verified+1

Verified that this passes all tests when applied internally, though I'm getting a weird com.google.gwt.dev.SoycTest error when I run it via "ant test":

Testcase: testSoyc took 22.948 sec
        Caused an ERROR
com.google.gwt.dev.js.JsObfuscateNamer.exec(Lcom/google/gwt/dev/js/ast/JsProgram;[Lcom/google/gwt/core/ext/PropertyOracle;)V
java.lang.NoSuchMethodError: com.google.gwt.dev.js.JsObfuscateNamer.exec(Lcom/google/gwt/dev/js/ast/JsProgram;[Lcom/google/gwt/core/ext/PropertyOracle;)V
        at com.google.gwt.core.ext.linker.impl.StandardLinkerContext.optimizeJavaScript(StandardLinkerContext.java:452)

I'll retry to see if it's a fluke.  (Running the test via our internal build system doesn't give this error.)

Patch-set: 4
Reviewer: Gerrit User 5000 <5000@84fdd5b9-d3fc-3149-9ae9-e619898c4c46>
Label: Verified=+1