Update patch set 1
Patch Set 1:

Tested from within Eclipse, the argument is correctly parsed and applied, but it then fails:

   Saving source to savedSources
 [ERROR] Unexpected internal compiler error
java.lang.IllegalArgumentException: Negative time
	at java.io.File.setLastModified(File.java:1344)
	at com.google.gwt.dev.util.OutputFileSetOnDirectory$1.close(OutputFileSetOnDirectory.java:58)
	at com.google.gwt.dev.SourceSaver.copySourceFile(SourceSaver.java:221)
	at com.google.gwt.dev.SourceSaver.copySources(SourceSaver.java:125)
	at com.google.gwt.dev.SourceSaver.save(SourceSaver.java:101)
	at com.google.gwt.dev.Link.doProduceOutput(Link.java:419)
	at com.google.gwt.dev.Link.link(Link.java:178)
	at com.google.gwt.dev.Compiler.run(Compiler.java:200)
	at com.google.gwt.dev.Compiler.run(Compiler.java:132)
	at com.google.gwt.dev.Compiler$1.run(Compiler.java:99)
	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
	at com.google.gwt.dev.Compiler.main(Compiler.java:106)

This is because SourceSaver uses OpenFileSet#openForWriter(String) which hard-codes lastModifiedTime to -1. This is a different issue though. For information, I'm running OpenJDK 7 on Ubuntu 13.10.

Patch-set: 1